name: easy_web_view
description: A super simple webview for Flutter Web and Mobile
version: 1.4.0-nullsafety
homepage: https://github.com/rodydavis/easy_web_view
repository: https://github.com/rodydavis/plugins
maintainer: Rody Davis (@rodydavis)
environment:
  sdk: ">=2.12.0-259.8.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.0-nullsafety.4
  flutter_markdown: ^0.6.0-nullsafety.1
  markdown: ^4.0.0-nullsafety.0
  html2md: ^0.5.1
  url_launcher: ^6.0.0-nullsafety.6
  http: ^0.13.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
